# Breakdown Configuration
params:
  two:
    directiveType:
      pattern: "^(analyze|analyze-structure)$"
    layerType:
      pattern: "^(requirements)$"
options:
  destination:
    prefix: "drafts/spec/result/yyyy/mm/yyyy-mm-dd-hh-"
